### ISSUE TITLE
Importing post5.js throws reference error - in examples too

### ISSUE THREAD

**Issue by zetenynagy** [bandaloo/post5#3]
If I try to use post5 in any of my own projects, or if I try to run the examples, I get the following error:

```
ReferenceError: Can't find variable: info
    at mpInit (/post5.js:4211:13)

    at (anonymous function) (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.js:48986:25)

    at forEach ([native code])

    at p5 (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.js:48984:51)

    at _globalInit (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.js:48197:34)

    at promiseReactionJob ([native code])

🌸 p5.js says: It seems that you may have accidently written info instead of int (on line 4211 in blob:https://preview.p5js.org/670c3bd7-010f-47d1-b962-df67665cac53 [blob:https://preview.p5js.org/670c3bd7-010f-47d1-b962-df67665cac53:4211:13]).

Please correct it to int if you wish to use the function from p5.js (http://p5js.org/reference/#/p5/int) 
```

**Comment by bandaloo** [comment]
@zetenynagy thanks for bringing this up; i'll look into it

**Comment by zetenynagy** [comment]
might be worth mentioning that i only tested it using editor.p5js.org - i don't know if it still happens using a different IDE
